name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: true # Continue workflow even if this step fails

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: failure() # Only run this job if the build job fails
    steps:
      - name: Send failure notification
        run: |
          echo "Build or tests failed"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Build or tests failed"}' YOUR_WEBHOOK_URLs


        